### PR TITLE
All functionality has been added.

### PR DESCRIPTION
**Pull request by sagar117**

### CODE REVIEW

**Comment by prabhakar267** [comment]
Hi @sagar117 
Can you please explain what all functionalities you have added and what exactly is your code doing?

**Comment by sagar117** [comment]
@prabhakar267
As you mentioned in issue you wanted bro display all images on a page of particular URL and then button for download them as a zip.

**Comment by prabhakar267** [comment]
@sagar117 Can you please explain the usage for the same?
Because I am not able to understand how the code is working.

**Comment by prabhakar267** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
